-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  OBSOLETO — No ejecutar.                                       ║
-- ║  La fuente de verdad del esquema es el script ejecutado en el  ║
-- ║  Prompt 1 (creación inicial de la BD). Las tablas `ventas` y   ║
-- ║  `detalle_ventas` ya existen con la siguiente estructura real:  ║
-- ║                                                                 ║
-- ║  ventas:                                                        ║
-- ║    id_venta INT AUTO_INCREMENT PRIMARY KEY,                     ║
-- ║    id_usuario INT NOT NULL,                                     ║
-- ║    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                   ║
-- ║    total DECIMAL(10,2) NOT NULL,                                ║
-- ║    hash_datos VARCHAR(255) NOT NULL,                            ║
-- ║    firma_digital TEXT NOT NULL,                                 ║
-- ║    estado ENUM('pendiente','confirmada','anulada')              ║
-- ║         NOT NULL DEFAULT 'confirmada',                          ║
-- ║    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)     ║
-- ║                                                                 ║
-- ║  detalle_ventas:                                                ║
-- ║    id_detalle INT AUTO_INCREMENT PRIMARY KEY,                   ║
-- ║    id_venta INT NOT NULL,                                       ║
-- ║    id_producto INT NOT NULL,                                    ║
-- ║    cantidad INT NOT NULL,                                       ║
-- ║    precio_unitario DECIMAL(10,2) NOT NULL,                      ║
-- ║    subtotal DECIMAL(10,2) NOT NULL,                             ║
-- ║    FOREIGN KEY ...                                              ║
-- ║                                                                 ║
-- ║  Este archivo se conserva solo como referencia histórica del    ║
-- ║  Prompt 7. NO debe ejecutarse.                                 ║
-- ╚══════════════════════════════════════════════════════════════════╝
-- Schema obsoleto — vea comentario arriba.
