<?php
require dirname(__DIR__) . '/app/config/config.php';
require dirname(__DIR__) . '/vendor/autoload.php';
function ok(bool $v,string $m):void{echo($v?'[OK] ':'[FAIL] ').$m.PHP_EOL;if(!$v)throw new RuntimeException($m);}
function req(string $u,string $c,?array $p=null):array{$h=curl_init($u);curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEJAR=>$c,CURLOPT_COOKIEFILE=>$c]);if($p!==null)curl_setopt_array($h,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($p)]);$r=curl_exec($h);if($r===false)throw new RuntimeException(curl_error($h));$n=curl_getinfo($h,CURLINFO_HEADER_SIZE);return[curl_getinfo($h,CURLINFO_RESPONSE_CODE),substr($r,$n)];}
function token(string $h):string{preg_match('/name="csrf_token" value="([^"]+)"/',$h,$m);return html_entity_decode($m[1]??'');}
function signin(string $e,string $p,string $c):void{[, $h]=req(BASE_URL.'auth/login',$c);[$s]=req(BASE_URL.'auth/login',$c,['email'=>$e,'password'=>$p,'csrf_token'=>token($h)]);ok($s===302,'Inicio de sesión HTTP');}
$db=Database::getInstance()->getConnection();$x=bin2hex(random_bytes(4));$pid=0;$uids=[];$ac=tempnam(sys_get_temp_dir(),'pa');$cc=tempnam(sys_get_temp_dir(),'pc');
try{
 $lang=(new Idioma())->buscarPorCodigo('es');$pass='Prueba123';foreach(['admin','cliente']as$r)$uids[]=(new Usuario())->crear(['nombre'=>'HTTP '.$r,'email'=>"{$r}-{$x}@example.test",'password_hash'=>password_hash($pass,PASSWORD_BCRYPT),'id_idioma'=>$lang['id_idioma'],'rol'=>$r,'activo'=>1]);
 signin("admin-{$x}@example.test",$pass,$ac);[$s,$h]=req(BASE_URL.'proveedor/crear',$ac);ok($s===200&&str_contains($h,'Registrar proveedor'),'Abrir nuevo proveedor');$t=token($h);
 [$s]=req(BASE_URL.'proveedor/guardar',$ac,['csrf_token'=>$t,'nombre'=>'Proveedor HTTP '.$x,'telefono'=>'+507 300-0000','celular'=>'+507 6000-0000','email'=>'inicial-'.$x.'@example.test','sitio_web'=>'proveedor.example','direccion'=>'Vía Central 123','ciudad'=>'Ciudad de Panamá','calificacion_estrellas'=>'0','notas'=>'Prueba']);ok($s===302,'Registrar proveedor');
 $q=$db->prepare('SELECT * FROM proveedores WHERE nombre=:n');$q->execute([':n'=>'Proveedor HTTP '.$x]);$p=$q->fetch();$pid=(int)$p['id_proveedor'];ok($p&&$p['sitio_web']==='https://proveedor.example'&&(int)$p['calificacion_estrellas']===0,'BD, URL sin protocolo y estrellas 0');[, $list]=req(BASE_URL.'proveedor/admin',$ac);ok(str_contains($list,'Proveedor HTTP '.$x),'Aparece en listado');
 [$s,$h]=req(BASE_URL.'proveedor/editar/'.$pid,$ac);ok($s===200&&str_contains($h,'value="Proveedor HTTP '.$x.'"')&&str_contains($h,'+507 300-0000'),'Edición precarga valores');$t=token($h);
 [$s]=req(BASE_URL.'proveedor/actualizar/'.$pid,$ac,['csrf_token'=>$t,'nombre'=>'Proveedor Actualizado '.$x,'telefono'=>'+507 399-9999','celular'=>'+507 6999-9999','email'=>'actualizado-'.$x.'@example.test','sitio_web'=>'https://nuevo.example','direccion'=>'Avenida Nueva 456','ciudad'=>'Colón','calificacion_estrellas'=>'5','notas'=>'Actualizado','activo'=>'1']);ok($s===302,'Actualizar por POST');$p=(new ProveedorModel())->buscarPorId($pid);ok($p['nombre']==='Proveedor Actualizado '.$x&&$p['telefono']==='+507 399-9999'&&$p['email']==='actualizado-'.$x.'@example.test'&&$p['direccion']==='Avenida Nueva 456'&&$p['ciudad']==='Colón'&&$p['sitio_web']==='https://nuevo.example'&&(int)$p['calificacion_estrellas']===5,'UPDATE completo y estrellas 5');
 [$s]=req(BASE_URL.'proveedor/actualizar/'.$pid,$ac,['nombre'=>'Sin CSRF']);ok($s===403,'POST sin CSRF');[$s]=req(BASE_URL.'proveedor/editar/999999999',$ac);ok($s===404,'ID inexistente 404');
 [, $h]=req(BASE_URL.'proveedor/editar/'.$pid,$ac);req(BASE_URL.'proveedor/actualizar/'.$pid,$ac,['csrf_token'=>token($h),'nombre'=>'Valor conservado','email'=>'correo-invalido','sitio_web'=>'sitio.example','calificacion_estrellas'=>'3','activo'=>'1']);[, $h]=req(BASE_URL.'proveedor/editar/'.$pid,$ac);ok(str_contains($h,'Valor conservado')&&str_contains($h,'correo electrónico válido'),'Validación conserva valores');
 signin("cliente-{$x}@example.test",$pass,$cc);[$s]=req(BASE_URL.'proveedor/editar/'.$pid,$cc);ok($s===302,'Cliente rechazado');
}finally{if($pid)$db->prepare('DELETE FROM proveedores WHERE id_proveedor=:id')->execute([':id'=>$pid]);foreach($uids as$id)$db->prepare('DELETE FROM usuarios WHERE id_usuario=:id')->execute([':id'=>$id]);@unlink($ac);@unlink($cc);}
