<?php
require dirname(__DIR__) . '/app/config/config.php';
require dirname(__DIR__) . '/vendor/autoload.php';
function cartOk(bool $v,string $m):void{echo($v?'[OK] ':'[FAIL] ').$m.PHP_EOL;if(!$v)throw new RuntimeException($m);}
function cartReq(string $url,string $cookie,?array $post=null):array{$h=curl_init($url);curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_COOKIEFILE=>$cookie]);if($post!==null)curl_setopt_array($h,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($post)]);$raw=curl_exec($h);if($raw===false)throw new RuntimeException(curl_error($h));$n=curl_getinfo($h,CURLINFO_HEADER_SIZE);return[curl_getinfo($h,CURLINFO_RESPONSE_CODE),substr($raw,$n),substr($raw,0,$n)];}
function cartToken(string $html):string{preg_match('/name="csrf_token" value="([^"]+)"/',$html,$m);return html_entity_decode($m[1]??'');}
function cartLogin(string $email,string $password,string $cookie):void{[, $html]=cartReq(BASE_URL.'auth/login',$cookie);[$s]=cartReq(BASE_URL.'auth/login',$cookie,['email'=>$email,'password'=>$password,'csrf_token'=>cartToken($html)]);cartOk($s===302,'Login de '.$email);}
$db=Database::getInstance()->getConnection();$product=$db->query('SELECT id_producto FROM productos WHERE activo=1 AND cantidad>0 LIMIT 1')->fetch();if(!$product)throw new RuntimeException('Se requiere un producto activo con stock.');$pid=(int)$product['id_producto'];$x=bin2hex(random_bytes(4));$ids=[];$cookies=[];
try{
 $idioma=(new Idioma())->buscarPorCodigo('es');$pass='Prueba123';foreach(['cliente','admin']as$rol)$ids[$rol]=(new Usuario())->crear(['nombre'=>'Cart '.$rol,'email'=>"cart-{$rol}-{$x}@example.test",'password_hash'=>password_hash($pass,PASSWORD_BCRYPT),'id_idioma'=>$idioma['id_idioma'],'rol'=>$rol,'activo'=>1]);foreach(['visitante','cliente','admin']as$r)$cookies[$r]=tempnam(sys_get_temp_dir(),'cart-');
 [$s,$catalog]=cartReq(BASE_URL.'producto',$cookies['visitante']);cartOk($s===200,'Visitante puede ver catálogo');[$s]=cartReq(BASE_URL.'producto/detalle/'.$pid,$cookies['visitante']);cartOk($s===200,'Visitante puede ver detalle');[$s,, $headers]=cartReq(BASE_URL.'carrito/agregar/'.$pid,$cookies['visitante'],['csrf_token'=>cartToken($catalog),'cantidad'=>1]);cartOk($s===302&&str_contains($headers,'auth/login'),'Visitante es redirigido al login al comprar');[, $login]=cartReq(BASE_URL.'auth/login',$cookies['visitante']);cartOk(str_contains($login,'Debe iniciar sesión como cliente'),'Login muestra mensaje al visitante');
 cartLogin("cart-cliente-{$x}@example.test",$pass,$cookies['cliente']);[, $catalog]=cartReq(BASE_URL.'producto',$cookies['cliente']);[$s]=cartReq(BASE_URL.'carrito/agregar/'.$pid,$cookies['cliente'],['csrf_token'=>cartToken($catalog),'cantidad'=>1]);cartOk($s===302,'Cliente puede agregar al carrito');[$s,$cart]=cartReq(BASE_URL.'carrito/ver',$cookies['cliente']);cartOk($s===200&&str_contains($cart,'Proceder al pago'),'Cliente puede ver y modificar carrito');[$s]=cartReq(BASE_URL.'venta/checkout',$cookies['cliente']);cartOk($s===200,'Cliente activo puede abrir checkout');
 cartLogin("cart-admin-{$x}@example.test",$pass,$cookies['admin']);[$s,$adminCatalog]=cartReq(BASE_URL.'producto',$cookies['admin']);cartOk($s===200,'Administrador puede ver catálogo');cartOk(!str_contains($adminCatalog,'carrito/agregar')&&!str_contains($adminCatalog,'href="'.BASE_URL.'carrito/ver"'),'Administrador no ve botones ni icono del carrito');[$s,$detail]=cartReq(BASE_URL.'producto/detalle/'.$pid,$cookies['admin']);cartOk($s===200&&!str_contains($detail,'carrito/agregar'),'Administrador ve detalle sin agregar');[$s]=cartReq(BASE_URL.'carrito/ver',$cookies['admin']);cartOk($s===403,'Administrador recibe 403 en carrito');[$s]=cartReq(BASE_URL.'venta/checkout',$cookies['admin']);cartOk($s===403,'Administrador recibe 403 en checkout');[$s]=cartReq(BASE_URL.'carrito/agregar/'.$pid,$cookies['admin'],['csrf_token'=>cartToken($adminCatalog),'cantidad'=>1]);cartOk($s===403,'POST manual de administrador recibe 403 aun con CSRF');
}finally{foreach($ids as$id)$db->prepare('DELETE FROM usuarios WHERE id_usuario=:id')->execute([':id'=>$id]);foreach($cookies as$c)@unlink($c);}
